name: Release-PROD
on:
  workflow_dispatch:

env:
  NODE_VERSION: 18
  BUILD_NUMBER: $GITHUB_RUN_NUMBER
  APP_ENV: production
  BUCKET_NAME: "meanfi-production"
  ROBOTS_TXT_FILE_NAME: "robots_allow.txt"
  ARTIFACT_NAME: mean-ui-build-production
  DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID_PROD }}
  AWS_S3_SKIP_FOLDERS: 5 # keep only last 5 deploys
  APPROVAL_ADMINS_PROD: MexicanSparker,welldan97,eydelrivero,micheltriana
  MINIMUM_APPROVALS: 1

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      # Get Approval
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ env.APPROVAL_ADMINS_PROD }}
          minimum-approvals: ${{ env.MINIMUM_APPROVALS }}
          issue-title: "Deploying to PROD for build number #${{ github.run_number }}"

  build:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "yarn"

      # Cache node modules
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # Install Yarn
      - name: Install packages
        run: yarn install

        # Build react app
      - name: Generate build for ${{ env.APP_ENV }}
        run: npm run build:s3
        env:
          REACT_APP_ENV: ${{ env.APP_ENV }}

      # Copy the appropiate robots.txt
      - name: Copy robots.txt
        run: cp ci/${{ env.ROBOTS_TXT_FILE_NAME }} build/robots.txt

      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build
          retention-days: 30

  deploy:
    runs-on: ubuntu-latest
    # When application is successfully tested and build has been generated
    # Then we can start with deployment
    needs: build
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}

      # Set the credentials from repository settings/secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Copy the files from build folder to the S3 bucket
      - name: Deploy to S3
        env:
          AWS_S3_PATH: "s3://${{ env.BUCKET_NAME }}/v${{ github.run_number }}"
        run: |
          aws s3 sync . ${{env.AWS_S3_PATH}}/ --acl public-read --cache-control 'public, max-age=604800' --exclude 'index.html'
          aws s3 cp index.html ${{env.AWS_S3_PATH}}/index.html --acl public-read --cache-control max-age=0
        working-directory: .

      # Updates the distribution origin path
      - name: Update originPath
        uses: mean-dao/aws-web-deploy@v1
        env:
          FOLDER_PATH: "/v${{ github.run_number }}"
        with:
          ORIGIN_PATH: "/v${{ github.run_number }}"
          AWS_DISTRIBUTION_ID: ${{ env.DISTRIBUTION_ID }}
          AWS_S3_PATH: "s3://${{ env.BUCKET_NAME }}/v${{ github.run_number }}"

      # get list of folders and remove older ones
      - name: S3 Cleanup
        run: |
          FOLDERS_TO_DELETE="$(aws s3 ls s3://${{ env.BUCKET_NAME }} | awk -Fv '{print $2}' | awk -F/ '{print $1}' | sort -n -r | awk '{if(NR > ${{ env.AWS_S3_SKIP_FOLDERS }}) print $0}')"
          for FOLDER_NO in $FOLDERS_TO_DELETE
          do
            echo "Removing s3://${{ env.BUCKET_NAME }}/v$FOLDER_NO ..."
            aws s3 rm s3://${{ env.BUCKET_NAME }}/v$FOLDER_NO/ --recursive
          done
